package it.niko.mywatchlist.entities;

public enum EGenre {
    DRAMA, CRIME, SCI_FI, COMEDY, FANTASY, ANIMATION,
    SITCOM, REALITY, SOAP_OPERA, TELENOVELA, DOCUMENTARY,
    ACTION, EDUCATIONAL, SPORTS, HORROR, ROMANCE, SATIRICAL,
    SUPERNATURAL, SCIENCE, SCHOOL, TIME_TRAVEL, HISTORICAL,
    ADVENTURE, THRILLER, WAR
}
